variables:
  SCHEDULER_PARAMETERS: "-pgeneral -t 1:00:00 -N 1 --ntasks-per-node=16"
  GIT_STRATEGY: clone
  NPROCS: 4

stages:
  - build
  - test

build:master:
  stage: build
  tags: [darwin-slurm-shared]
  script:
    - module load gcc
    -  git clone git@github.com:spack/spack.git
    -  pushd spack
    -  . share/spack/setup-env.sh
    - spack env activate -d ../gnu_master_x86_64
    - spack concretize -f
    - spack install
    - spack env loads
    - module use --append $PWD/share/spack/modules/linux-centos7-x86_64
    - module avail
    - popd
    - source gnu_master_x86_64/loads
    - pushd tests
    - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - spack
      - tests
    expire_in: 1 week

test:master:
  stage: test
  tags: [darwin-slurm-shared]
  dependencies:
    - build:master
  needs: ["build:master"]
  script:
    - pwd
    - module load gcc
    - pushd spack
    -  . share/spack/setup-env.sh
    - spack env activate -d ../gnu_master_x86_64
    - module use --append $PWD/share/spack/modules/linux-centos7-x86_64
    - popd
    - source gnu_master_x86_64/loads
    - pushd tests
    - mpirun -np 4 hostname
    - mpirun -np 4 ./hello_c
    - mpirun -np 4 ./ring_c
    - mpirun -np 4 ./hello_mpifh
    - mpirun -np 4 ./ring_mpifh
    - mpirun -np 4 ./hello_usempi
    - mpirun -np 4 ./ring_usempi
    - mpirun -np 4 ./hello_usempif08
    - mpirun -np 4 ./ring_usempif08
    - mpirun -np 4 ./connectivity_c
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 1 week
