variables:
  GIT_STRATEGY: clone
  NPROCS: 4

stages:
  - build_m
  - build_r

build:master:
  stage: build_m
  tags: [jlsebatch2,shell]
  script:
    - module load oneapi
    - export SPACK_DISABLE_LOCAL_CONFIG=true
    - export SPACK_USER_CACHE_PATH=$PWD/sc_m
    -  git clone git@github.com:spack/spack.git
    -  pushd spack
    -  . share/spack/setup-env.sh
    - spack env activate -d ../intel_master_x86_64
    - spack concretize -f
    - spack install --fail-fast
    - spack env loads
    - ls $PWD/share/spack/modules
    - module use --append $PWD/share/spack/modules/linux-opensuse15-x86_64
    - module avail
    - popd
    - source intel_master_x86_64/loads
    - pushd tests
    - make
    - mpirun -np 4 hostname
    - mpirun -np 4 ./hello_c
    - mpirun -np 4 ./ring_c
    - mpirun -np 4 ./hello_mpifh
    - mpirun -np 4 ./ring_mpifh
    - mpirun -np 4 ./hello_usempi
    - mpirun -np 4 ./ring_usempi
    - mpirun -np 4 ./hello_usempif08
    - mpirun -np 4 ./ring_usempif08
    - mpirun -np 4 ./connectivity_c
    - popd
    - git clone https://github.com/E4S-Project/testsuite
    - pushd testsuite
    - ./test-all.sh --color-off ./validation_tests/openmpi
  variables:
    JLSE_SCHEDULER_PARAMETERS: "-qarcticus -t 1:00:00 -n 1"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    expire_in: 1 week

build:release:
  stage: build_r
  tags: [jlsebatch2,shell]
  dependencies:
    - build:master
  script:
    - module load oneapi
    - export SPACK_DISABLE_LOCAL_CONFIG=true
    - export SPACK_USER_CACHE_PATH=$PWD/sc_r
    - rm -f -r spack
    -  git clone git@github.com:spack/spack.git
    -  pushd spack
    -  . share/spack/setup-env.sh
    - spack env activate -d ../intel_release_x86_64
    - spack concretize -f
    - spack install --fail-fast
    - spack env loads
    - module use --append $PWD/share/spack/modules/linux-opensuse15-x86_64
    - module avail
    - popd
    - source intel_release_x86_64/loads
    - pushd tests
    - make
    - mpirun -np 4 hostname
    - mpirun -np 4 ./hello_c
    - mpirun -np 4 ./ring_c
    - mpirun -np 4 ./hello_mpifh
    - mpirun -np 4 ./ring_mpifh
    - mpirun -np 4 ./hello_usempi
    - mpirun -np 4 ./ring_usempi
    - mpirun -np 4 ./hello_usempif08
    - mpirun -np 4 ./ring_usempif08
    - mpirun -np 4 ./connectivity_c
    - popd
    - git clone https://github.com/E4S-Project/testsuite
    - pushd testsuite
    - ./test-all.sh --color-off ./validation_tests/openmpi
  variables:
    JLSE_SCHEDULER_PARAMETERS: "-qarcticus -t 1:00:00 -n 1"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    expire_in: 1 week
